### PR TITLE
prepare release

### PR DESCRIPTION
**Pull request by soerenmartius**

### CODE REVIEW

**Comment by mariux** [comment]
@soerenmartius pls also merge #15 before release.

**Comment by soerenmartius** [comment]
Requires #16 to be merged

**Comment by soerenmartius** [comment]
> Requires #16 to be merged

Converting to draft until all dependencies are merged

**Comment by soerenmartius** [comment]
r4r @mariux

**Comment by soerenmartius** [comment]
> lgtm... but now we are missing a test that checks if setting no-domain still works..

feel free to add one :)

**Pull request merged**
