### PR TITLE
fix!: Fix idempotency issue of device tracking by adding new `user_device_tracking` variable

### LINKED ISSUE #23: terraform state is not idempotent if device tracking is off
I am unable to use device tracking currently because of the limitation it places on using refresh tokens.

I am able to successfully turn device tracking off by using this combination of parameters

```hcl
  device_only_remembered_on_user_prompt = null
  challenge_required_on_new_device = null
```

but the result is that a change is always detected:

image

- Should I not be using this module if I don't need device tracking?
- is there a way to ignore these lifecycle changes (I don't think you can pass lifecycle blocks in modules, but I am not sure)

Alternatively I could open a PR? Maybe add an enable_device_tracking boolean parameter that would omit the device_configuration block if false?

### PR DESCRIPTION
**Pull request by mariux**
### BREAKING CHANGES
- fix!: Fix idempotency issue of device tracking by adding user_device_tracking variable
- release: Prepare 0.3.0 release

fixes #23

### CODE REVIEW

**Comment by mariux** [comment]
@soerenmartius tested against our staging cognito. Added migration hints to changelog.

**Review by soerenmartius — DISMISSED** [review]
LGTM!

**Comment by soerenmartius** [comment]
Thanks for fixing this :)

**Review by soerenmartius — APPROVED** [review]
lgtm!

**Pull request merged**
